name: dart_movies_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins-Black
      fonts:
        - asset: lib/assets/fonts/Poppins-Black.ttf
    - family: Poppins-Bold
      fonts:
        - asset: lib/assets/fonts/Poppins-Bold.ttf
    - family: Poppins-ExtraBold
      fonts:
        - asset: lib/assets/fonts/Poppins-ExtraBold.ttf
    - family: Poppins-ExtraLight
      fonts:
        - asset: lib/assets/fonts/Poppins-ExtraLight.ttf
    - family: Poppins-Light
      fonts:
        - asset: lib/assets/fonts/Poppins-Light.ttf
    - family: Poppins-Medium
      fonts:
        - asset: lib/assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Regular
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-Thin
      fonts:
        - asset: lib/assets/fonts/Poppins-Thin.ttf
    
